import { mkdirSync, writeFileSync, rmSync, copyFileSync } from 'node:fs';
import path from 'node:path';

const outDir = 'dist';
const repoName = 'labor-rights-tools';
const siteUrl = process.env.SITE_URL || `https://zfq123hh.github.io/${repoName}`;
const basePath = process.env.BASE_PATH || `/${repoName}`;
const email = 'fuquanz617@gmail.com';

const cities = [
  ['beijing','北京'],['shanghai','上海'],['guangzhou','广州'],['shenzhen','深圳'],['hangzhou','杭州'],['nanjing','南京'],['suzhou','苏州'],['chengdu','成都'],['chongqing','重庆'],['wuhan','武汉'],['xian','西安'],['tianjin','天津'],['qingdao','青岛'],['ningbo','宁波'],['xiamen','厦门'],['fuzhou','福州'],['jinan','济南'],['zhengzhou','郑州'],['changsha','长沙'],['hefei','合肥'],['kunming','昆明'],['nanchang','南昌'],['shenyang','沈阳'],['dalian','大连'],['changchun','长春'],['harbin','哈尔滨'],['shijiazhuang','石家庄'],['taiyuan','太原'],['huhehaote','呼和浩特'],['lanzhou','兰州'],['yinchuan','银川'],['xining','西宁'],['urumqi','乌鲁木齐'],['haikou','海口'],['sanya','三亚'],['dongguan','东莞'],['foshan','佛山'],['zhuhai','珠海'],['zhongshan','中山'],['huizhou','惠州'],['wuxi','无锡'],['changzhou','常州'],['nantong','南通'],['xuzhou','徐州'],['jiaxing','嘉兴'],['shaoxing','绍兴'],['wenzhou','温州'],['jinhua','金华'],['quanzhou','泉州'],['yantai','烟台'],['weifang','潍坊'],['luoyang','洛阳'],['guilin','桂林'],['nanning','南宁'],['guiyang','贵阳'],['mianyang','绵阳'],['baoding','保定'],['langfang','廊坊'],['tangshan','唐山'],['qinhuangdao','秦皇岛'],['lhasa','拉萨'],['dali','大理'],['yichang','宜昌'],['xiangyang','襄阳'],['liuzhou','柳州'],['wuhu','芜湖'],['maanshan','马鞍山'],['taizhou-zj','台州'],['taizhou-js','泰州'],['yangzhou','扬州'],['zhenjiang','镇江'],['yancheng','盐城'],['huaian','淮安'],['lianyungang','连云港'],['suqian','宿迁'],['huzhou','湖州'],['quzhou','衢州'],['lishui','丽水']
];
const uniqueCities = Array.from(new Map(cities.map(c=>[c[0],c])).values());

const tools = {
  severance: {
    slug: 'severance',
    name: '离职补偿N+1计算器',
    short: '离职补偿',
    title: '离职补偿N+1计算器｜经济补偿金、代通知金、违法解除赔偿估算',
    desc: '输入月工资、工作年限、当地月平均工资等，估算经济补偿金N、代通知金+1、违法解除2N参考金额。',
    keywords: ['离职补偿N+1怎么算','经济补偿金计算器','违法解除赔偿2N','代通知金计算']
  },
  overtime: {
    slug: 'overtime-pay',
    name: '加班费计算器', short: '加班费',
    title: '加班费计算器｜工作日150%、休息日200%、法定节假日300%估算',
    desc: '按月工资、计薪天数、日薪/小时工资估算工作日、休息日、法定节假日加班费。',
    keywords: ['加班费怎么算','周末加班费计算器','法定节假日三倍工资','小时工资计算']
  },
  annual: {
    slug: 'annual-leave',
    name: '年假工资计算器', short: '年假工资',
    title: '未休年假工资计算器｜应休年假天数、未休年假补偿估算',
    desc: '根据累计工作年限、已休年假和月工资，估算未休年假工资补偿参考金额。',
    keywords: ['未休年假工资怎么算','年假天数计算器','年休假补偿','年假工资300%']
  },
  sick: {
    slug: 'sick-pay',
    name: '病假工资计算器', short: '病假工资',
    title: '病假工资计算器｜病假期间工资、医疗期工资估算',
    desc: '按月工资、病假天数和支付比例，估算病假期间工资参考金额。各地规则差异较大，请以本地规定为准。',
    keywords: ['病假工资怎么算','医疗期工资计算器','病假扣工资合法吗','病假工资比例']
  }
};

function esc(s='') { return String(s).replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c])); }
function url(p='') { const clean = p.startsWith('/') ? p : `/${p}`; return `${basePath}${clean}`.replace(/\/\/$/, '/'); }
function absUrl(p='') { const clean = p.startsWith('/') ? p : `/${p}`; return `${siteUrl}${clean}`.replace(/\/\/$/, '/'); }
function write(rel, html) { const file = path.join(outDir, rel, 'index.html'); mkdirSync(path.dirname(file), {recursive:true}); writeFileSync(file, html, 'utf8'); }
function asset(rel, content) { const file = path.join(outDir, rel); mkdirSync(path.dirname(file), {recursive:true}); writeFileSync(file, content, 'utf8'); }

const css = `
:root{--bg:#f7f8fb;--card:#fff;--text:#111827;--muted:#667085;--line:#e5e7eb;--brand:#175cd3;--accent:#f59e0b;--ok:#067647;--danger:#b42318}*{box-sizing:border-box}body{margin:0;font-family:-apple-system,BlinkMacSystemFont,"Segoe UI","PingFang SC","Microsoft YaHei",Arial,sans-serif;background:var(--bg);color:var(--text);line-height:1.7}.wrap{max-width:1120px;margin:0 auto;padding:0 18px}header{background:#fff;border-bottom:1px solid var(--line);position:sticky;top:0;z-index:10}nav{display:flex;justify-content:space-between;align-items:center;min-height:64px;gap:18px}.brand{font-weight:800;color:var(--text);text-decoration:none;font-size:20px}.nav a{color:#344054;text-decoration:none;margin-left:16px}.hero{padding:56px 0 32px;background:linear-gradient(135deg,#eef4ff,#fff7ed)}h1{font-size:42px;line-height:1.15;margin:0 0 16px}h2{font-size:28px;margin:34px 0 14px}h3{font-size:20px;margin:22px 0 8px}.lead{font-size:19px;color:#475467;max-width:820px}.grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(240px,1fr));gap:16px}.card{background:var(--card);border:1px solid var(--line);border-radius:18px;padding:20px;box-shadow:0 8px 22px rgba(16,24,40,.04)}.card a{text-decoration:none;color:var(--brand);font-weight:700}.pill{display:inline-block;background:#e0eaff;color:#1849a9;padding:4px 10px;border-radius:999px;font-size:13px;margin:3px}.btn{display:inline-block;background:var(--brand);color:white!important;text-decoration:none;padding:11px 16px;border-radius:999px;font-weight:750;margin:8px 8px 8px 0}.btn.secondary{background:#fff;color:var(--brand)!important;border:1px solid #b2ccff}.calc{display:grid;grid-template-columns:1fr 1fr;gap:18px;align-items:start}.form label{display:block;font-weight:700;margin:12px 0 5px}.form input,.form select,.form textarea{width:100%;border:1px solid #d0d5dd;border-radius:12px;padding:11px;font-size:16px;background:#fff}.result{background:#101828;color:white;border-radius:18px;padding:20px;position:sticky;top:84px}.result strong{font-size:32px;color:#fef08a}.note{font-size:14px;color:#667085}.warn{border-left:5px solid var(--accent);background:#fffaeb;padding:12px;border-radius:12px}.danger{border-left:5px solid var(--danger);background:#fef3f2;padding:12px;border-radius:12px}.table{width:100%;border-collapse:collapse;background:#fff;border-radius:16px;overflow:hidden}.table th,.table td{border-bottom:1px solid var(--line);padding:11px;text-align:left}.footer{margin-top:48px;padding:28px 0;color:#667085;border-top:1px solid var(--line)}.small{font-size:13px;color:#667085}.kpi{font-size:30px;font-weight:800}.breadcrumbs{font-size:14px;color:#667085;margin:14px 0}.list a{display:block;padding:8px 0;color:var(--brand);text-decoration:none}@media(max-width:760px){h1{font-size:32px}.calc{grid-template-columns:1fr}.result{position:static}.nav a{margin-left:8px;font-size:14px}}
`;

const appjs = `
function yuan(n){ if(!isFinite(n)) return '¥0'; return '¥' + Math.max(0,n).toLocaleString('zh-CN',{maximumFractionDigits:2}); }
function num(id){ return parseFloat(document.getElementById(id)?.value||'0')||0; }
function set(id, v){ const el=document.getElementById(id); if(el) el.textContent=v; }
function calcSeverance(){ const wage=num('wage'), years=num('years'), avg=num('avg'), notice=document.getElementById('notice')?.value==='yes'; const cap=avg>0?avg*3:Infinity; const base=Math.min(wage,cap); const n=Math.max(0,years); const comp=base*n; const noticePay=notice?wage:0; const illegal=comp*2; set('r1', yuan(comp)); set('r2', yuan(noticePay)); set('r3', yuan(comp+noticePay)); set('r4', yuan(illegal)); }
function calcOvertime(){ const wage=num('wage'), workday=num('workday'), rest=num('rest'), holiday=num('holiday'), days=num('days')||21.75; const day=wage/days; const hour=day/8; const total=hour*workday*1.5 + hour*rest*2 + hour*holiday*3; set('r1', yuan(day)); set('r2', yuan(hour)); set('r3', yuan(total)); }
function legalAnnualDays(totalYears){ if(totalYears<1) return 0; if(totalYears<10) return 5; if(totalYears<20) return 10; return 15; }
function calcAnnual(){ const wage=num('wage'), totalYears=num('totalYears'), used=num('used'), days=num('days')||21.75; const annual=legalAnnualDays(totalYears); const unused=Math.max(0, annual-used); const day=wage/days; const pay=day*unused*2; set('r1', annual+' 天'); set('r2', unused+' 天'); set('r3', yuan(pay)); }
function calcSick(){ const wage=num('wage'), sickDays=num('sickDays'), ratio=num('ratio')/100, days=num('days')||21.75; const day=wage/days; const pay=day*sickDays*ratio; set('r1', yuan(day)); set('r2', yuan(pay)); }
document.addEventListener('input',()=>{ if(document.body.dataset.tool==='severance') calcSeverance(); if(document.body.dataset.tool==='overtime') calcOvertime(); if(document.body.dataset.tool==='annual') calcAnnual(); if(document.body.dataset.tool==='sick') calcSick(); });
document.addEventListener('DOMContentLoaded',()=>{ calcSeverance(); calcOvertime(); calcAnnual(); calcSick(); });
`;

function layout({title, desc, body, tool}) {
  const schema = {"@context":"https://schema.org","@type":"WebSite",name:'劳动权益计算器',url:siteUrl,description:'劳动权益、离职补偿、加班费、年假工资、病假工资在线估算工具'};
  return `<!doctype html><html lang="zh-CN"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${esc(title)}</title><meta name="description" content="${esc(desc)}"><link rel="stylesheet" href="${url('/assets/style.css')}"><script type="application/ld+json">${JSON.stringify(schema)}</script></head><body data-tool="${tool||''}"><header><div class="wrap"><nav><a class="brand" href="${url('/')}">劳动权益计算器</a><div class="nav"><a href="${url('/tools/')}">工具</a><a href="${url('/cities/')}">城市</a><a href="${url('/templates/')}">模板包</a><a href="${url('/guides/labor-arbitration-evidence-checklist/')}">证据清单</a><a href="${url('/sponsor/')}">合作变现</a><a href="${url('/contact/')}">联系</a></div></nav></div></header>${body}<footer class="footer"><div class="wrap"><p>© ${new Date().getFullYear()} 劳动权益计算器｜个人估算参考，不构成法律意见。</p><p><a href="${url('/privacy/')}">隐私</a> · <a href="${url('/terms/')}">条款</a> · <a href="${url('/contact/')}">联系/合作</a></p></div></footer><script src="${url('/assets/app.js')}"></script></body></html>`;
}

function toolCards(){return Object.values(tools).map(t=>`<div class="card"><h3>${t.name}</h3><p>${t.desc}</p><p>${t.keywords.map(k=>`<span class="pill">${k}</span>`).join('')}</p><a class="btn secondary" href="${url(`/tools/${t.slug}/`)}">打开工具</a></div>`).join('');}
function cityLinks(toolKey){ const t=tools[toolKey]; return uniqueCities.map(([slug,name])=>`<a href="${url(`/cities/${slug}/${t.slug}/`)}">${name}${t.short}怎么算</a>`).join(''); }

function home(){
  return layout({title:'劳动权益计算器｜离职补偿N+1、加班费、年假工资、病假工资在线估算', desc:'提供离职补偿N+1、经济补偿金、加班费、未休年假工资、病假工资在线估算工具，覆盖重点城市长尾查询。', body:`<section class="hero"><div class="wrap"><h1>把劳动权益问题变成可计算的金额</h1><p class="lead">离职补偿、N+1、违法解除2N、加班费、未休年假、病假工资，一页输入，立即得到保守估算。适合员工自查、HR初算、律师/咨询机构获客。</p><a class="btn" href="${url('/tools/severance/')}">先算离职补偿</a><a class="btn secondary" href="${url('/templates/')}">查看模板包清单</a><a class="btn secondary" href="${url('/guides/labor-arbitration-evidence-checklist/')}">查看仲裁证据清单</a><a class="btn secondary" href="${url('/guides/labor-arbitration-application-template/')}">查看仲裁申请书模板</a><a class="btn secondary" href="${url('/guides/no-written-contract-double-wage/')}">未签合同双倍工资</a><a class="btn secondary" href="${url('/guides/fixed-term-contract-nonrenewal/')}">合同到期不续签补偿</a><a class="btn secondary" href="${url('/guides/pregnancy-dismissal/')}">孕期被辞退赔偿</a><a class="btn secondary" href="${url('/guides/noncompete-compensation/')}">竞业限制补偿金</a><a class="btn secondary" href="${url('/sponsor/')}">查看合作变现入口</a></div></section><main class="wrap"><h2>核心工具</h2><div class="grid">${toolCards()}</div><h2>为什么这个站可以变现</h2><div class="grid"><div class="card"><div class="kpi">高痛点</div><p>离职、裁员、欠加班费是强需求，用户搜索时已经有明确金额焦虑。</p></div><div class="card"><div class="kpi">高客单</div><p>劳动纠纷咨询、律师线索、企业HR合规服务，比普通广告点击更值钱。</p></div><div class="card"><div class="kpi">可扩展</div><p>城市 × 场景 × 问法可持续生成SEO页，不需要主动拉人。</p></div></div><h2>重点城市入口</h2><div class="card list">${uniqueCities.slice(0,36).map(([s,n])=>`<a href="${url(`/cities/${s}/severance/`)}">${n}离职补偿N+1计算器</a>`).join('')}</div></main>`});
}

function toolsIndex(){ return layout({title:'劳动权益工具大全｜离职补偿、加班费、年假工资、病假工资', desc:'劳动权益相关在线计算器列表。', body:`<main class="wrap"><div class="breadcrumbs"><a href="${url('/')}">首页</a> / 工具</div><h1>劳动权益工具大全</h1><p class="lead">先用保守口径估算金额，再决定是否咨询专业人士。</p><div class="grid">${toolCards()}</div></main>`}); }

function calcBlock(toolKey){
 if(toolKey==='severance') return `<section class="calc"><div class="card form"><label>月工资/解除前平均月工资（元）</label><input id="wage" type="number" value="12000"><label>工作年限N（年，可填小数，如 3.5）</label><input id="years" type="number" step="0.5" value="3"><label>当地职工月平均工资（可选，用于3倍封顶）</label><input id="avg" type="number" value="10000"><label>是否估算代通知金 +1</label><select id="notice"><option value="yes">是，估算N+1</option><option value="no">否，只算N</option></select></div><div class="result"><p>经济补偿金 N</p><strong id="r1">¥0</strong><p>代通知金 +1</p><strong id="r2">¥0</strong><p>N+1合计参考</p><strong id="r3">¥0</strong><p>违法解除 2N 参考</p><strong id="r4">¥0</strong></div></section>`;
 if(toolKey==='overtime') return `<section class="calc"><div class="card form"><label>月工资（元）</label><input id="wage" type="number" value="12000"><label>月计薪天数</label><input id="days" type="number" value="21.75"><label>工作日加班小时</label><input id="workday" type="number" value="10"><label>休息日加班小时</label><input id="rest" type="number" value="8"><label>法定节假日加班小时</label><input id="holiday" type="number" value="0"></div><div class="result"><p>日工资参考</p><strong id="r1">¥0</strong><p>小时工资参考</p><strong id="r2">¥0</strong><p>加班费合计</p><strong id="r3">¥0</strong></div></section>`;
 if(toolKey==='annual') return `<section class="calc"><div class="card form"><label>月工资（元）</label><input id="wage" type="number" value="12000"><label>累计工作年限（年）</label><input id="totalYears" type="number" value="6"><label>当年已休年假天数</label><input id="used" type="number" value="0"><label>月计薪天数</label><input id="days" type="number" value="21.75"></div><div class="result"><p>应休年假</p><strong id="r1">0天</strong><p>未休天数</p><strong id="r2">0天</strong><p>未休年假额外补偿参考</p><strong id="r3">¥0</strong></div></section>`;
 return `<section class="calc"><div class="card form"><label>月工资（元）</label><input id="wage" type="number" value="12000"><label>病假天数</label><input id="sickDays" type="number" value="5"><label>支付比例（%）</label><input id="ratio" type="number" value="80"><label>月计薪天数</label><input id="days" type="number" value="21.75"></div><div class="result"><p>日工资参考</p><strong id="r1">¥0</strong><p>病假工资参考</p><strong id="r2">¥0</strong></div></section>`;
}

function toolPage(toolKey, city){
 const t = tools[toolKey]; const cityText = city ? `${city[1]}` : '';
 const title = city ? `${city[1]}${t.title}` : t.title;
 const desc = city ? `${city[1]}${t.desc}` : t.desc;
 const cityPara = city ? `<p class="warn">${city[1]}本地实际口径可能受最低工资、当地平均工资、地方规定、合同约定和证据影响。本页只做${city[1]}用户的个人估算参考。</p>` : '';
 const related = Object.entries(tools).filter(([k])=>k!==toolKey).map(([k,ot])=>`<a href="${url(city?`/cities/${city[0]}/${ot.slug}/`:`/tools/${ot.slug}/`)}">${cityText}${ot.name}</a>`).join('');
 const citySection = !city ? `<h2>按城市查看${t.short}</h2><div class="card list">${cityLinks(toolKey)}</div>` : '';
 const body = `<main class="wrap"><div class="breadcrumbs"><a href="${url('/')}">首页</a> / <a href="${url('/tools/')}">工具</a> / ${esc(cityText+t.name)}</div><h1>${esc(cityText+t.name)}</h1><p class="lead">${esc(desc)}</p>${cityPara}${calcBlock(toolKey)}<h2>计算口径说明</h2><div class="card"><ul><li>本工具采用常见公开规则做个人估算，不替代仲裁、诉讼、税务或律师意见。</li><li>离职补偿中的“N”通常和工作年限相关；“+1”通常指未提前通知时的代通知金；违法解除可能涉及2N口径。</li><li>加班费、年假、病假工资会受考勤、合同、规章制度、地方规定和证据影响。</li></ul></div><h2>下一步怎么把金额变成可主张材料</h2><div class="grid"><div class="card"><h3>1. 留存证据</h3><p>劳动合同、工资流水、社保记录、考勤、加班审批、聊天记录、解除通知。</p></div><div class="card"><h3>2. 明确诉求</h3><p>把经济补偿、代通知金、加班费、未休年假、工资差额分别列清。</p></div><div class="card"><h3>3. 找专业人士复核</h3><p>如果金额较大，建议让律师/劳动仲裁咨询机构结合证据复核。</p></div></div><h2>相关工具</h2><div class="card list">${related}</div>${citySection}<div class="danger"><b>免责声明：</b>本页只做个人估算参考，不构成法律意见；具体结果以当地法规、仲裁/法院认定和专业人士意见为准。</div></main>`;
 return layout({title, desc, body, tool: toolKey});
}

function citiesIndex(){ return layout({title:'城市劳动权益计算器｜各城市离职补偿、加班费、年假工资', desc:'按城市查看离职补偿N+1、加班费、年假工资、病假工资估算。', body:`<main class="wrap"><div class="breadcrumbs"><a href="${url('/')}">首页</a> / 城市</div><h1>按城市查看劳动权益计算器</h1><p class="lead">城市页用于覆盖“城市 + 劳动权益 + 计算器”长尾搜索。</p><div class="grid">${uniqueCities.map(([s,n])=>`<div class="card"><h3>${n}</h3><p><a href="${url(`/cities/${s}/severance/`)}">离职补偿</a> · <a href="${url(`/cities/${s}/overtime-pay/`)}">加班费</a> · <a href="${url(`/cities/${s}/annual-leave/`)}">年假</a> · <a href="${url(`/cities/${s}/sick-pay/`)}">病假工资</a></p></div>`).join('')}</div></main>`}); }
function simplePage(slug,title,desc,html){ write(slug, layout({title,desc,body:`<main class="wrap"><h1>${title}</h1>${html}</main>`})); }

rmSync(outDir,{recursive:true,force:true}); mkdirSync(outDir,{recursive:true});
asset('assets/style.css', css); asset('assets/app.js', appjs); asset('.nojekyll','');
write('', home()); write('tools', toolsIndex()); write('cities', citiesIndex());
for (const [key,t] of Object.entries(tools)) write(`tools/${t.slug}`, toolPage(key));
for (const city of uniqueCities) for (const [key,t] of Object.entries(tools)) write(`cities/${city[0]}/${t.slug}`, toolPage(key, city));
simplePage('guides/labor-arbitration-evidence-checklist','劳动仲裁证据清单｜离职补偿、加班费、年假工资维权材料整理','劳动仲裁前需要准备哪些证据？按劳动合同、工资流水、社保、考勤、加班、解除通知和沟通记录整理材料，适合离职补偿、加班费、未休年假自查。',`<p class="lead">把计算器结果转成可复核材料：先确认诉求金额，再按证据类型整理原件、截图和时间线，减少咨询律师或申请仲裁时的遗漏。</p><div class="grid"><div class="card"><h3>1. 身份与劳动关系</h3><p>劳动合同、入职登记、工牌/门禁、工作邮箱、社保缴费记录、个税记录、工资条或银行流水。</p></div><div class="card"><h3>2. 工资与工时</h3><p>工资流水、工资结构说明、考勤记录、排班表、加班审批、调休记录、绩效/提成规则。</p></div><div class="card"><h3>3. 解除或争议事实</h3><p>解除通知、协商记录、聊天记录、录音要点、离职证明、工作交接文件、公司规章制度。</p></div></div><h2>按诉求拆分证据</h2><div class="card list"><a href="${url('/tools/severance/')}">离职补偿N+1：工作年限、解除原因、平均工资</a><a href="${url('/tools/overtime-pay/')}">加班费：考勤、加班安排、未调休证明</a><a href="${url('/tools/annual-leave/')}">未休年假：累计工龄、已休天数、工资基数</a><a href="${url('/tools/sick-pay/')}">病假工资：病假材料、工资基数、公司支付比例</a></div><h2>7步整理时间线</h2><div class="card"><ol><li>列出入职、续签、调岗、调薪、离职/解除日期。</li><li>用计算器估算每项诉求金额，并单独保存截图或记录参数。</li><li>把证据按“劳动关系、工资、工时、解除事实、沟通记录”分文件夹。</li><li>给每份证据命名日期和来源，例如“2026-05工资流水-银行导出”。</li><li>截图保留完整聊天对象、时间、上下文，不只截单句话。</li><li>金额较大时，带着清单向律师/劳动仲裁咨询机构复核。</li><li>仅提交必要材料，身份证号、银行卡等敏感信息先做脱敏备份。</li></ol></div><h2>模板包入口</h2><p>需要把本清单变成表格，可进入模板包页面查看“证据清单、加班台账、年假台账、离职补偿测算表”。</p><p><a class="btn" href="${url('/templates/')}">查看劳动权益模板包</a><a class="btn secondary" href="mailto:${email}?subject=劳动仲裁证据清单模板候补">申请证据清单模板候补</a></p><div class="danger"><b>免责声明：</b>本页仅用于材料整理和自查，不构成法律意见；具体证据采信和金额认定以当地法规、仲裁/法院及专业人士意见为准。</div>`);
simplePage('guides/overtime-pay-evidence-template','加班费证据清单与计算表模板｜考勤、审批、聊天记录整理','加班费证据怎么整理？按考勤记录、加班审批、聊天记录、工资流水和调休记录生成加班费计算表模板思路，适合劳动仲裁前自查。',`<p class="lead">很多加班费争议不是不会算，而是证据和计算表没有对应起来。本页把“加班事实、工资基数、倍率、已调休/已支付”拆成可复核字段，方便先自查再咨询专业人士。</p><div class="grid"><div class="card"><h3>1. 证明有加班安排</h3><p>保留排班表、考勤打卡、加班审批、值班表、项目上线通知、工作群安排和邮件记录，尽量体现日期、时段和负责人。</p></div><div class="card"><h3>2. 证明工资基数</h3><p>整理劳动合同、工资条、银行流水、个税记录和薪资结构说明，区分固定工资、绩效、补贴与已支付加班费。</p></div><div class="card"><h3>3. 证明没有足额补偿</h3><p>把调休记录、加班费发放记录、工资单备注逐月核对，标出未调休、未支付或低于法定倍率的部分。</p></div></div><h2>加班费计算表字段</h2><div class="card"><ol><li>日期：精确到哪一天，区分工作日、休息日、法定节假日。</li><li>开始/结束时间：建议按小时记录，并保留截图来源。</li><li>加班原因：项目、值班、盘点、线上故障、领导安排等。</li><li>工资基数：先用月工资除以21.75天、再折算小时工资做保守估算。</li><li>倍率：工作日150%、休息日200%、法定节假日300%；休息日已安排调休的要单独标注。</li><li>证据编号：每一行对应考勤、审批、聊天记录或邮件截图，便于复核。</li></ol></div><h2>先算金额，再整理材料</h2><p>可以先用加班费计算器估算总额，再把高金额月份优先补证据。若金额较大或证据存在争议，建议带着表格找律师/劳动仲裁咨询机构复核。</p><p><a class="btn" href="${url('/tools/overtime-pay/')}">打开加班费计算器</a><a class="btn secondary" href="${url('/templates/')}">查看模板包候补</a><a class="btn secondary" href="${url('/guides/labor-arbitration-evidence-checklist/')}">查看仲裁证据总清单</a></p><div class="danger"><b>免责声明：</b>本页只用于材料整理和个人估算参考，不构成法律意见；具体证据采信和金额认定以当地法规、仲裁/法院及专业人士意见为准。</div>`);
simplePage('guides/labor-arbitration-application-template','劳动仲裁申请书模板｜离职补偿、加班费、未休年假请求写法','劳动仲裁申请书怎么写？把离职补偿N+1、加班费、未休年假、病假工资等请求拆成可填写字段，适合提交前自查和咨询复核。',`<p class="lead">申请书不需要堆砌情绪，关键是把当事人、仲裁请求、事实理由、金额计算和证据编号写清楚。本页提供可复制的结构，方便先整理再请专业人士复核。</p><div class="grid"><div class="card"><h3>1. 基础信息</h3><p>写明申请人、被申请人、工作地点、入职日期、岗位、工资标准、劳动合同和社保缴纳情况。不要在公开渠道提交身份证号、银行卡等敏感信息。</p></div><div class="card"><h3>2. 仲裁请求</h3><p>按项目拆分金额：经济补偿金、代通知金、违法解除赔偿、加班费、未休年假工资、工资差额或病假工资。每项请求单独列金额和期间。</p></div><div class="card"><h3>3. 事实与理由</h3><p>用时间线描述入职、调薪、加班、请假、解除或拖欠工资经过，并把每段事实对应到合同、工资流水、考勤、通知、聊天记录等证据。</p></div></div><h2>可复制的申请书结构</h2><div class="card"><ol><li>标题：劳动人事争议仲裁申请书。</li><li>当事人信息：申请人与用人单位名称、地址、联系方式。</li><li>仲裁请求：请求一、请求二、请求三，分别写清金额、计算区间和依据。</li><li>事实与理由：按时间线写，避免只写结论；每个事实后标注证据编号。</li><li>证据目录：劳动合同、工资流水、考勤记录、解除通知、聊天记录、社保/个税记录等。</li><li>结尾：提交仲裁委员会名称、申请人签名和日期。</li></ol></div><h2>常见请求写法示例</h2><div class="card"><ul><li>离职补偿：请求支付解除劳动合同经济补偿金人民币X元，计算方式为月平均工资X元 × 工作年限N。</li><li>N+1/代通知金：请求支付未提前三十日通知解除劳动合同的代通知金人民币X元。</li><li>加班费：请求支付某年某月至某年某月期间延时、休息日或法定节假日加班费人民币X元。</li><li>未休年假：请求支付未休年休假工资报酬人民币X元，并列明应休、已休、未休天数。</li></ul></div><h2>先算金额，再写请求</h2><p>建议先用本站工具做保守估算，再把参数和证据编号填入申请书；金额较大、证据复杂或涉及违法解除时，提交前应找律师/劳动仲裁咨询机构复核。</p><p><a class="btn" href="${url('/tools/severance/')}">计算离职补偿</a><a class="btn secondary" href="${url('/tools/overtime-pay/')}">计算加班费</a><a class="btn secondary" href="${url('/guides/labor-arbitration-evidence-checklist/')}">查看证据清单</a><a class="btn secondary" href="mailto:${email}?subject=劳动仲裁申请书模板候补">申请模板候补</a></p><div class="danger"><b>免责声明：</b>本页只提供文书结构和材料整理思路，不构成法律意见；具体请求、金额和管辖请以当地仲裁机构要求及专业人士意见为准。</div>`);
simplePage('guides/no-written-contract-double-wage','未签劳动合同双倍工资怎么算｜未签合同赔偿计算与证据清单','未签劳动合同能主张双倍工资吗？梳理自用工之日起超过一个月不满一年未签书面劳动合同的二倍工资口径、最长11个月、证据和仲裁请求写法。',`<p class="lead">未签书面劳动合同是高频劳动争议。一般从入职满一个月后的次日起，到补签书面劳动合同前一日或满一年止，主张二倍工资差额；不同地区对仲裁时效、责任归属和证据采信有细节差异。</p><div class="grid"><div class="card"><h3>1. 什么时候能主张</h3><p>用人单位自用工之日起超过一个月不满一年未与劳动者订立书面劳动合同的，劳动者可围绕未签期间主张二倍工资差额。若劳动者拒签、单位已有书面通知或存在特殊用工安排，结果可能不同。</p></div><div class="card"><h3>2. 金额怎么粗算</h3><p>常见保守口径是：月工资基数 × 未签书面合同月数，最多按11个月估算；实际请求通常以已发工资之外的另一倍工资差额为主，具体以当地仲裁或法院口径为准。</p></div><div class="card"><h3>3. 为什么要先整理证据</h3><p>争议焦点通常不是公式，而是入职日期、工资基数、是否签过合同、是否补签、谁导致未签。证据越完整，咨询复核和仲裁请求越清楚。</p></div></div><h2>计算步骤</h2><div class="card"><ol><li>确定用工起始日：入职登记、工资流水、考勤、社保个税、工作群记录都可辅助证明。</li><li>确定未签期间：从入职满一个月后的次日起算，到补签书面合同前一日或满一年为止。</li><li>确定工资基数：优先用工资条、银行流水、个税记录和合同/录用通知中的薪资约定交叉核对。</li><li>估算金额：未签月数不足整月时可按实际天数或当地口径折算，先用保守金额作为咨询基础。</li><li>同时检查其他诉求：若已离职或被辞退，可同步估算离职补偿、欠薪、加班费和未休年假。</li></ol></div><h2>证据清单</h2><div class="card list"><a href="${url('/guides/labor-arbitration-evidence-checklist/')}">劳动关系证据：入职、工牌、邮箱、工作群、考勤</a><a href="${url('/tools/severance/')}">离职或辞退同时发生：先估算经济补偿N</a><a href="${url('/guides/labor-arbitration-application-template/')}">仲裁请求写法：把二倍工资差额单独列项</a><a href="${url('/templates/')}">模板包：证据目录和金额拆分表候补</a></div><h2>仲裁请求写法示例</h2><div class="card"><p>请求被申请人支付未签订书面劳动合同二倍工资差额人民币X元，期间为X年X月X日至X年X月X日，计算方式为月工资基数X元 × 未签书面劳动合同月数X个月。</p><p>如果同时存在欠薪、违法解除或未休年假，建议每项请求分别列金额、期间、计算方式和证据编号，避免混在一项里难以复核。</p></div><p><a class="btn" href="${url('/guides/labor-arbitration-evidence-checklist/')}">查看证据清单</a><a class="btn secondary" href="${url('/guides/labor-arbitration-application-template/')}">查看申请书模板</a><a class="btn secondary" href="${url('/tools/severance/')}">计算离职补偿</a></p><div class="danger"><b>免责声明：</b>本页只提供个人估算和材料整理思路，不构成法律意见；二倍工资差额、仲裁时效和证据采信以当地仲裁/法院及专业人士意见为准。</div>`);
simplePage('guides/probation-dismissal','试用期被辞退有赔偿吗？试用期解除劳动合同赔偿指南','试用期被辞退有没有N+1？试用期解除劳动合同的经济补偿、违法解除赔偿金计算和证据整理思路，区分合法解除、无过失解除和违法解除。',`<p class="lead">许多人在试用期被辞退时不清楚自己是否有赔偿。根据劳动合同法，试用期并非随意解雇期——只有在法定情形下才能无偿解除。本页帮你判断适用场景并估算参考金额。</p><div class="grid"><div class="card"><h3>试用期合法解除（无赔偿）</h3><p>被证明不符合录用条件、严重违反规章制度、严重失职造成重大损害、同时建立双重劳动关系影响工作或以欺诈手段使单位违背真实意思订立合同。以上情况用人单位可零成本解除。</p></div><div class="card"><h3>试用期无过失解除（有补偿N）</h3><p>劳动者医疗期满不能从事原工作、不能胜任工作经培训或调岗仍不能胜任、客观情况重大变化导致合同无法履行且协商未达成一致。需支付经济补偿N。</p></div><div class="card"><h3>试用期违法解除（2N赔偿）</h3><p>无任何法定依据、无法证明不符合录用条件、仅在试用期结束前口头通知辞退且无证据支持、以试用期不合适等模糊理由随意解除。可能构成违法解除，赔偿为2N。</p></div></div><h2>试用期N怎么算</h2><div class="card"><ul><li><b>工作年限N：</b>试用期天数按实际在岗天数折算为年（如3个月试用期通过后辞退，N约等于0.25年）。</li><li><b>月工资基数：</b>按解除前12个月平均工资计算，不足12个月按实际月份。</li><li><b>代通知金+1：</b>仅适用于无过失解除中未提前30天通知的情形，试用期一般较短但仍可主张。</li></ul></div><h2>先算金额，再判断情形</h2><p>使用离职补偿N+1计算器输入试用期月工资和工作年限（按月折算），先看保守估算金额，再根据用人单位给出的解除理由判断是否属于违法解除。</p><p><a class="btn" href="${url('/tools/severance/')}">打开离职补偿计算器</a><a class="btn secondary" href="${url('/guides/labor-arbitration-evidence-checklist/')}">查看仲裁证据清单</a><a class="btn secondary" href="${url('/guides/labor-arbitration-application-template/')}">查看仲裁申请书模板</a></p><h2>证明不符合录用条件需要什么</h2><div class="card"><p>如果用人单位以不符合录用条件为由辞退，需要证明：录用条件已书面告知（招聘JD、录用通知书、岗位说明书）、录用条件合理且可量化、考核结果证明未达标。缺少任何一项，辞退可能被认定为违法。</p></div><div class="danger"><b>免责声明：</b>试用期解除的金额认定以合同、规章制度、考核标准、解除通知和当地仲裁或法院意见为准，本页只做个人估算参考，不构成法律意见。</div>`);
simplePage('guides/wage-arrears','公司拖欠工资怎么办？拖欠工资补偿标准与维权流程','公司拖欠工资多久算违法？拖欠工资的加付赔偿金标准、劳动监察投诉流程、劳动仲裁申请思路和证据整理。',`<p class="lead">公司拖欠工资是劳动权益领域最紧迫的高频场景之一。先确定拖欠天数、金额，再按劳动监察、仲裁的顺序推进。部分情况可主张额外加付50%至100%的赔偿金。</p><div class="grid"><div class="card"><h3>劳动监察投诉（最快）</h3><p>适合单纯欠薪、事实清楚的情况。拨打12333或到当地劳动监察大队投诉。监察一般不处理经济补偿或加班费争议，适合先走这一步解决欠薪本身。</p></div><div class="card"><h3>劳动仲裁（全面主张）</h3><p>如果公司长期拖欠或同时涉及欠薪和离职补偿，可申请劳动仲裁。可主张拖欠工资本身、加付赔偿金以及以拖欠工资为由被迫解除的经济补偿N。</p></div><div class="card"><h3>法院强制执行</h3><p>仲裁裁决生效后公司仍不支付的，可申请法院强制执行。关注公司是否存在资产转移或清算，职工债权在企业破产时享有优先权。</p></div></div><h2>可主张的金额</h2><div class="card"><ul><li><b>拖欠工资本身：</b>未支付的正常工资，按合同约定或实际发放标准计算。</li><li><b>加付赔偿金：</b>劳动合同法第85条规定，责令限期支付后逾期仍不支付的，可加付50%至100%的额外赔偿（以劳动监察责令为准）。</li><li><b>被迫解除经济补偿：</b>以拖欠工资为由提出被迫解除合同，可主张经济补偿N。</li><li><b>加班费：</b>如果拖欠的是加班费，可以一并主张。</li></ul></div><h2>先核算金额，再收集证据</h2><p>使用加班费计算器和离职补偿计算器先把金额算清楚，再按拖欠月份整理工资条、银行流水、考勤记录和沟通记录。</p><p><a class="btn" href="${url('/tools/severance/')}">计算离职补偿</a><a class="btn secondary" href="${url('/tools/overtime-pay/')}">计算加班费</a><a class="btn secondary" href="${url('/guides/labor-arbitration-evidence-checklist/')}">查看证据清单</a></p><h2>关键时间线</h2><div class="card"><ol><li>记录拖欠开始月份、每个月应发和实发日期、拖欠金额。</li><li>保留工资条、银行流水截图、考勤记录与HR或财务沟通记录。</li><li>发送书面催告（邮件或微信），保留对方承认拖欠的记录。</li><li>到当地劳动监察投诉，索要受理回执。</li><li>如果监察调解失败或同时有离职补偿争议，立即申请劳动仲裁（仲裁时效通常为1年）。</li></ol></div><div class="danger"><b>免责声明：</b>加付赔偿金、被迫解除经济补偿等诉求以当地劳动监察、仲裁或法院的认定为准，本页只做个人估算和流程参考，不构成法律意见。</div>`);
simplePage('guides/constructive-dismissal','被迫离职怎么证明？调岗降薪不交社保的被迫解除劳动合同指南','被迫离职法律依据、被迫解除劳动合同通知写法、证据清单和经济补偿N的计算思路，聚焦调岗降薪、不交社保、拖欠工资场景。',`<p class="lead">用人单位调岗降薪、不交社保、拖欠工资、变相辞退等行为，劳动者可以被迫解除劳动合同并要求经济补偿N。关键是用书面证据证明是公司先违约，劳动者被迫提出解除。</p><div class="grid"><div class="card"><h3>哪些情形可以被迫解除</h3><p>拖欠劳动报酬或未足额支付、低于当地最低工资支付、未依法缴纳社保、规章制度违法损害权益、以欺诈胁迫手段订立或变更合同、变相强迫加班或限制人身自由等。</p></div><div class="card"><h3>被迫解除的流程</h3><p>第一步：书面通知用人单位，说明解除理由和法律依据；第二步：保留送达证据；第三步：在仲裁申请中明确被迫解除的请求；第四步：主张经济补偿N。</p></div><div class="card"><h3>常见失败原因</h3><p>只有口头表示、没有书面通知、解除理由写的是个人原因而非公司违约、发出通知后又继续上班很久才主张被迫解除。仲裁或法院会综合认定是否被迫。</p></div></div><h2>被迫解除通知写法要点</h2><div class="card"><ol><li>标题：被迫解除劳动合同通知书。</li><li>当事人信息：姓名、岗位加公司全称。</li><li>事实描述：列出公司违约行为的起止时间、具体金额和事实依据。</li><li>法律依据：引用劳动合同法第38条和第46条。</li><li>结算要求：要求支付拖欠工资、经济补偿N、加班费等。</li><li>日期和签名：手写签字，建议拍照或发EMS留底。</li></ol></div><h2>金额估算</h2><p>被迫解除可主张经济补偿N（按工作年限乘以月平均工资）。如果同时涉及拖欠工资、加班费或未休年假工资，可在同一仲裁案中一并主张。先算清楚总额再发通知。</p><p><a class="btn" href="${url('/tools/severance/')}">计算被迫解除经济补偿</a><a class="btn secondary" href="${url('/tools/overtime-pay/')}">计算加班费</a><a class="btn secondary" href="${url('/tools/annual-leave/')}">计算未休年假</a><a class="btn secondary" href="${url('/guides/labor-arbitration-application-template/')}">查看仲裁申请书</a></p><div class="danger"><b>免责声明：</b>被迫解除是否成立以及经济补偿金额以当地仲裁或法院认定为准，本页只提供通知结构和维权思路参考，不构成法律意见。</div>`);
simplePage('guides/fixed-term-contract-nonrenewal','劳动合同到期不续签有补偿吗｜合同到期经济补偿N计算指南','劳动合同到期不续签有没有经济补偿？区分单位不续签、降低条件续签劳动者拒绝、劳动者主动不续签，整理合同到期经济补偿N计算、证据和仲裁请求写法。',`<p class="lead">劳动合同到期不续签并不等于自动没有补偿。关键看是谁提出不续签、续签条件是否降低，以及用人单位是否依法终止。先判断情形，再用经济补偿N口径做保守估算。</p><div class="grid"><div class="card"><h3>单位不续签：通常有经济补偿N</h3><p>固定期限劳动合同期满，若用人单位决定不再续签，一般应按劳动者在本单位工作年限支付经济补偿。计算时关注合同期满前12个月平均工资、工作年限和当地三倍社平工资封顶。</p></div><div class="card"><h3>降低条件续签：劳动者拒绝也可能有补偿</h3><p>如果单位提出的续签条件低于原合同，例如降薪、降岗、缩短福利或改变关键工作条件，劳动者拒绝续签时，可重点保留续签通知、沟通记录和原合同条款，作为主张经济补偿的依据。</p></div><div class="card"><h3>维持或提高条件，劳动者主动不续签：通常无N</h3><p>若单位维持或提高劳动合同约定条件续订，而劳动者本人不同意续订，通常不能按合同到期终止主张经济补偿。仍可检查是否存在欠薪、加班费、未休年假等独立诉求。</p></div></div><h2>合同到期补偿N怎么估算</h2><div class="card"><ol><li>确认终止日期：以劳动合同到期日、终止通知、离职证明或最后工作日为准。</li><li>确认工作年限：在本单位每满一年按一个月工资，不满六个月按半个月，六个月以上不满一年按一个月做常见估算。</li><li>确认工资基数：通常用终止前12个月平均工资；不足12个月按实际工作月份整理。</li><li>检查封顶：高收入劳动者需关注当地上年度职工月平均工资三倍封顶及年限限制。</li><li>同步检查其他金额：合同到期时常伴随未休年假、欠薪、加班费或社保争议，建议分项列出。</li></ol></div><h2>证据清单</h2><div class="card list"><a href="${url('/tools/severance/')}">打开离职补偿N+1计算器估算金额</a><a href="${url('/guides/labor-arbitration-evidence-checklist/')}">整理劳动仲裁证据清单</a><a href="${url('/guides/labor-arbitration-application-template/')}">参考仲裁申请书请求写法</a><a href="${url('/tools/annual-leave/')}">同步估算未休年假工资</a><a href="${url('/templates/')}">下载/申请模板包候补</a></div><h2>仲裁请求写法示例</h2><div class="card"><p>请求被申请人支付劳动合同期满终止经济补偿金人民币X元，计算方式为终止前十二个月平均工资X元 × 本单位工作年限N。</p><p>若争议点是“降低条件续签”，建议在事实理由中列明原合同条件、单位提出的新条件、劳动者拒绝续签的时间和证据编号。</p></div><p><a class="btn" href="${url('/tools/severance/')}">计算合同到期补偿N</a><a class="btn secondary" href="${url('/guides/labor-arbitration-evidence-checklist/')}">查看证据清单</a><a class="btn secondary" href="mailto:${email}?subject=合同到期不续签模板候补">申请模板候补</a></p><div class="danger"><b>免责声明：</b>本页只提供个人估算和材料整理思路，不构成法律意见；合同到期终止、续签条件和经济补偿认定以当地仲裁/法院及专业人士意见为准。</div>`);
simplePage('guides/pregnancy-dismissal','孕期被辞退赔偿怎么算｜三期女职工解除劳动合同赔偿指南','孕期、产期、哺乳期被辞退怎么赔？梳理三期女职工违法解除2N、工资待遇、社保生育津贴和证据清单，适合劳动仲裁前自查。',`<p class="lead">孕期、产期、哺乳期属于劳动关系中的高风险解除场景。若单位没有法定依据单方解除，通常需要重点核查违法解除赔偿2N、工资待遇、社保和生育津贴是否受影响。本页先给出自查路径，便于提交咨询或劳动仲裁前整理事实。</p><div class="grid"><div class="card"><h3>1. 先判断是否仍在三期</h3><p>确认怀孕证明、预产期、产假起止、哺乳期截止时间，以及公司知悉时间。保存医院材料、请假记录、告知HR或主管的沟通记录。</p></div><div class="card"><h3>2. 判断解除理由是否成立</h3><p>公司以组织调整、绩效不合格、试用期不通过、合同到期等理由解除时，要看是否有充分制度依据、考核证据和合法流程。三期并非绝对不能解除，但违法解除风险更高。</p></div><div class="card"><h3>3. 拆分可主张金额</h3><p>常见项目包括违法解除赔偿2N、拖欠工资、产假工资/生育津贴差额、社保补缴情形、未休年假和加班费。建议逐项列金额和证据编号。</p></div></div><h2>赔偿金额怎么先粗算</h2><div class="card"><ol><li>用解除前12个月平均工资作为基数，不足12个月按实际月份整理。</li><li>按本单位工作年限估算经济补偿N，再用2N作为违法解除赔偿参考。</li><li>如果同时存在未发工资、产假待遇差额或社保断缴情形，单独列项，不要混进2N。</li><li>金额较大、证据复杂或公司要求签离职协议时，先复核再签字。</li></ol></div><h2>证据清单</h2><div class="card list"><a href="${url('/tools/severance/')}">用离职补偿N+1计算器估算2N金额</a><a href="${url('/guides/labor-arbitration-evidence-checklist/')}">整理劳动仲裁证据总清单</a><a href="${url('/guides/labor-arbitration-application-template/')}">参考仲裁申请书请求写法</a><a href="${url('/templates/')}">申请证据目录和金额拆分表模板</a></div><h2>沟通与签字提醒</h2><div class="card"><ul><li>不要只听口头承诺，解除、调岗、降薪、停薪、停社保都应保留书面材料。</li><li>离职协议、补偿协议、放弃仲裁声明等文件，签字前先核对金额和条款。</li><li>若公司要求写个人原因离职，而实际是被辞退或被迫离职，需要谨慎处理书面理由。</li></ul></div><p><a class="btn" href="${url('/tools/severance/')}">计算违法解除2N参考金额</a><a class="btn secondary" href="mailto:${email}?subject=孕期被辞退证据清单候补">申请孕期被辞退证据清单候补</a></p><div class="danger"><b>免责声明：</b>本页只提供个人估算和材料整理思路，不构成法律意见；三期女职工解除、待遇差额和社保生育津贴问题以当地法规、仲裁/法院及专业人士意见为准。</div>`);
simplePage('guides/noncompete-compensation','竞业限制补偿金计算指南｜竞业限制期限、补偿比例、违约后果','竞业限制补偿金怎么算？未约定补偿金可以主张吗？竞业限制期限最长几年？梳理竞业限制补偿金最低标准、未约定补偿时的处理路径和违反竞业限制的违约金估算思路。',`<p class="lead">竞业限制是用人单位与特定劳动者约定的离职后义务。劳动者履行了竞业限制义务，就有权要求用人单位支付经济补偿。很多人离职时签了竞业限制协议但不知道补偿金该拿多少、怎么拿。本页帮你先判断是否适用、再估算补偿金。</p><div class="grid"><div class="card"><h3>谁可能被竞业限制</h3><p>通常适用于高级管理人员、高级技术人员和其他负有保密义务的人员。普通员工、非涉密岗位、实习期或试用期较短员工被要求签竞业限制协议的，可重点关注是否属于法定范围。</p></div><div class="card"><h3>竞业限制期限多长</h3><p>根据劳动合同法，竞业限制期限不得超过二年。超过二年的部分通常不被支持。期限计算从离职之日或实际起算日开始，以协议约定为准。</p></div><div class="card"><h3>补偿金最低标准</h3><p>常见参考口径为离职前十二个月平均月工资的30%；若该标准低于当地最低工资标准，按最低工资标准执行。各地对"30%"和"月平均工资"的认定口径有细节差异。</p></div></div><h2>补偿金估算步骤</h2><div class="card"><ol><li>确定离职前12个月平均工资：包含基本工资、绩效、奖金、补贴等，按实发前口径整理工资条、银行流水和个税记录。</li><li>估算月补偿金基数：平均工资的30%。若协议中另有约定且不低于法定口径，按协议执行。</li><li>确定竞业限制期限：按协议约定月数计算，最多不得超过24个月。</li><li>估算总额：月补偿金 × 竞业限制月数。同时检查协议中是否约定违约金，以及违约金是否过高。</li></ol></div><h2>常见情形处理思路</h2><div class="card"><ul><li><b>协议未约定补偿金：</b>劳动者履行了竞业限制义务的，可要求按离职前12个月平均工资的30%按月支付。双方可协商，协商不成可通过仲裁确定。</li><li><b>单位三个月未支付补偿金：</b>劳动者有权请求解除竞业限制约定。解除后不再受竞业限制约束，也无需再主张补偿金。</li><li><b>违约金约定过高：</b>违约金以实际损失为参考，过高部分可请求仲裁或法院调减。注意保留单位实际损失难以证明的材料。</li><li><b>单位单方解除竞业限制：</b>用人单位有权在竞业限制期内解除，但劳动者可要求额外三个月的补偿金作为救济。</li></ul></div><h2>证据清单</h2><div class="card list"><a href="${url('/guides/labor-arbitration-evidence-checklist/')}">劳动仲裁证据总清单参考</a><a href="${url('/guides/labor-arbitration-application-template/')}">仲裁申请书仲裁请求写法</a><a href="${url('/tools/severance/')}">离职补偿N+1计算器</a></div><h2>仲裁请求写法示例</h2><div class="card"><p>请求被申请人支付竞业限制经济补偿金人民币X元，计算方式为离职前十二个月平均工资X元 × 30% × 竞业限制月数X个月。</p><p>若同时主张解除竞业限制，请求确认自X年X月X日起解除双方签订的《竞业限制协议》。</p></div><p><a class="btn" href="${url('/guides/labor-arbitration-evidence-checklist/')}">查看证据清单</a><a class="btn secondary" href="${url('/templates/')}">申请模板包候补</a><a class="btn secondary" href="mailto:${email}?subject=竞业限制补偿金材料候补">申请材料模板候补</a></p><div class="danger"><b>免责声明：</b>本页只提供个人估算和材料整理思路，不构成法律意见；竞业限制适用对象、补偿金比例和违约金金额以当地法规、仲裁/法院及专业人士意见为准。</div>`);
simplePage('templates','劳动权益模板包｜证据清单、加班台账、年假台账、离职补偿测算表','劳动权益计算器配套模板包清单，适合个人维权自查、HR合规台账和律师咨询前材料整理。',`<p class="lead">把计算结果转成可复核材料：先按模板整理证据、金额和时间线，再决定是否咨询律师或劳动仲裁机构。</p><div class="grid"><div class="card"><h3>个人维权材料包</h3><p>包含劳动合同/工资流水/社保/考勤/解除通知证据清单、仲裁请求金额拆分表、沟通记录整理表。</p><p><span class="pill">离职补偿</span><span class="pill">加班费</span><span class="pill">未休年假</span></p></div><div class="card"><h3>HR合规台账包</h3><p>包含加班审批台账、调休记录、年假余额台账、病假工资核算记录，便于企业做低风险自查。</p><p><span class="pill">HR合规</span><span class="pill">台账</span><span class="pill">复核</span></p></div><div class="card"><h3>咨询前准备清单</h3><p>面向律师/咨询机构线索转化：用户先补齐关键事实，减少无效沟通，提高付费咨询转化率。</p><p><span class="pill">律师线索</span><span class="pill">咨询转化</span></p></div></div><h2>适合搜索的问题</h2><div class="card list"><a href="${url('/guides/labor-arbitration-evidence-checklist/')}">劳动仲裁证据清单怎么整理</a><a href="${url('/tools/severance/')}">离职补偿N+1证据清单</a><a href="${url('/guides/overtime-pay-evidence-template/')}">加班费计算表模板</a><a href="${url('/guides/labor-arbitration-application-template/')}">劳动仲裁申请书模板</a><a href="${url('/guides/fixed-term-contract-nonrenewal/')}">劳动合同到期不续签补偿证据清单</a><a href="${url('/guides/pregnancy-dismissal/')}">孕期被辞退赔偿证据清单</a><a href="${url('/guides/no-written-contract-double-wage/')}">未签劳动合同双倍工资证据清单</a><a href="${url('/tools/annual-leave/')}">未休年假台账模板</a><a href="${url('/tools/sick-pay/')}">病假工资核算模板</a></div><h2>获取方式</h2><p>当前先开放候补和合作咨询，不收集敏感个人信息。需要模板包、赞助或联合线索页，请邮件说明城市、角色和使用场景。</p><p><a class="btn" href="mailto:${email}?subject=劳动权益模板包候补">申请模板包候补：${email}</a><a class="btn secondary" href="${url('/sponsor/')}">查看合作模式</a></p><div class="danger"><b>提示：</b>模板只用于材料整理和金额复核，不构成法律意见。</div>`);
simplePage('sponsor','合作变现｜律师线索、企业合规、模板包赞助','劳动权益计算器合作变现入口。',`<p class="lead">本站目标是通过劳动权益长尾搜索获取高意向用户，再用合作广告、律师/咨询线索、企业HR合规工具包和模板包变现。</p><div class="grid"><div class="card"><h3>律师/咨询合作</h3><p>适合劳动争议律师、劳动仲裁咨询、企业合规顾问获取高意向咨询线索。</p></div><div class="card"><h3>企业HR工具包</h3><p>可扩展为裁员测算、加班合规、年假台账、病假工资台账等付费模板。</p></div><div class="card"><h3>广告/赞助位</h3><p>城市页、工具页可投放合规服务入口。早期按月低价测试，后期按线索价值定价。</p></div></div><p><a class="btn" href="mailto:${email}?subject=劳动权益计算器合作">联系合作：${email}</a></p>`);
simplePage('contact','联系/合作','劳动权益计算器联系合作方式。',`<p>合作、赞助、纠错、模板包销售入口开通，请邮件联系：</p><p><a class="btn" href="mailto:${email}">${email}</a></p>`);
simplePage('privacy','隐私政策','隐私政策。',`<p>本站目前为静态工具站，计算过程在浏览器本地完成，不主动收集身份证号、手机号、工资流水等敏感信息。若通过邮件联系，邮件内容由用户主动提供。</p>`);
simplePage('terms','使用条款与免责声明','使用条款与免责声明。',`<p>本站所有计算结果仅供个人估算参考，不构成法律、税务、仲裁或诉讼意见。具体金额需结合劳动合同、工资记录、考勤证据、当地规定和专业人士意见判断。</p>`);

const urls = [];
urls.push('/'); urls.push('/tools/'); urls.push('/cities/'); urls.push('/guides/labor-arbitration-evidence-checklist/'); urls.push('/guides/overtime-pay-evidence-template/'); urls.push('/guides/labor-arbitration-application-template/'); urls.push('/guides/no-written-contract-double-wage/'); urls.push('/guides/probation-dismissal/'); urls.push('/guides/wage-arrears/'); urls.push('/guides/constructive-dismissal/'); urls.push('/guides/fixed-term-contract-nonrenewal/'); urls.push('/guides/pregnancy-dismissal/'); urls.push('/guides/noncompete-compensation/'); urls.push('/templates/'); urls.push('/sponsor/'); urls.push('/contact/'); urls.push('/privacy/'); urls.push('/terms/');
for (const t of Object.values(tools)) urls.push(`/tools/${t.slug}/`);
for (const city of uniqueCities) for (const t of Object.values(tools)) urls.push(`/cities/${city[0]}/${t.slug}/`);
asset('sitemap.xml', `<?xml version="1.0" encoding="UTF-8"?>\n<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">\n${urls.map(u=>`  <url><loc>${absUrl(u)}</loc></url>`).join('\n')}\n</urlset>`);
asset('robots.txt', `User-agent: *\nAllow: /\nSitemap: ${absUrl('/sitemap.xml')}\n`);
asset('page-manifest.json', JSON.stringify({siteUrl, basePath, pages: urls.length, cities: uniqueCities.length, tools: Object.keys(tools).length, generatedAt: new Date().toISOString()}, null, 2));
console.log(`Built ${urls.length} pages to ${outDir}`);
